<?php
/**
 * Created by PhpStorm.
 * User: gogl92
 * Date: 10/20/18
 * Time: 9:07 PM
 */

namespace inquid\howlerjs;


use yii\base\Widget;
use yii\helpers\Json;

class HowlerJsSimple extends Widget
{
    public $songs = ["http://www.largesound.com/ashborytour/sound/brobob.mp3"];
    public $options = ['loop' => false];
    public $volume = null;
    public $loop = false;
    public $preload = true;
    public $autoplay = false;
    public $mute = false;
    //TODO add more options
    public function init()
    {
        $assets = HowlerJsAssets::register($this->view);
        $assets->css = [];
        $this->view->registerJs('
        var sound = new Howl({
        html5:true,
      src:' . Json::encode($this->songs) . ',
                ' . (!empty($this->volume) ? 'volume :' . $this->volume . ',' : null) . '
                ' . (!empty($this->loop) ? 'loop :' . $this->loop . ',' : null) . '
                ' . (!empty($this->preload) ? 'preload :' . $this->preload . ',' : null) . '
                ' . (!empty($this->autoplay) ? 'autoplay :' . $this->autoplay . ',' : null) . '
                ' . (!empty($this->mute) ? 'mute :' . $this->mute . ',' : null) . '
    });
sound.play();
        ');
    }

    public function render($view, $params = [])
    {
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}